<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'violuke\\Barcodes' => array($vendorDir . '/violuke/php-barcodes/src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
);
