<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Smalot\\PdfParser\\' => array($vendorDir . '/smalot/pdfparser/src'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Luracast\\Restler' => array($vendorDir . '/restler/framework'),
    'Detection' => array($vendorDir . '/mobiledetect/mobiledetectlib/namespaced'),
    'ChromePhp' => array($vendorDir . '/ccampbell/chromephp'),
);
